name: rotina sexta 9 de resumo de notícias
on:
  schedule:
      - cron: '* * * * *' 

jobs:
  run-script-and-commit-changes:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: true

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests supabase openai

    - name: Run the script
      env:
        SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python resumos_semanais.py


    - name: Commit changes
      run: |
        git config --local user.email "hugoalmeidamoreira@gmail.com"
        git config --local user.name "Bender"
        git add -A
        git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)

    - name: push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
